//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by NHibernate.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;

namespace MyFramework.Common.NHibernate.Domain
{
	/// <summary>
	/// a class mapping for the table: user_info
	/// </summary>
	public  partial class User 
	{

	#region private fields
		Int64 _id;	
		String _name;	
		String _password;	
		DateTime? _birthday;	
		Int32? _role;	/* RoleId */
	#endregion
		
	#region getter/setters		
		/// <summary>
		///		
		/// </summary>
		public virtual Int64 Id
		{
			get{ return _id; }
			set{ _id = value; }
		}
		/// <summary>
		///		
		/// </summary>
		public virtual String Name
		{
			get{ return _name; }
			set{ _name = value; }
		}
		/// <summary>
		///		
		/// </summary>
		public virtual String Password
		{
			get{ return _password; }
			set{ _password = value; }
		}
		/// <summary>
		///		
		/// </summary>
		public virtual DateTime? Birthday
		{
			get{ return _birthday; }
			set{ _birthday = value; }
		}
		/// <summary>
		///		
		/// </summary>
		public virtual Int32? Role
		{
			get{ return _role; }
			set{ _role = value; }
		}
	#endregion
	}
}