// <auto-generated />
namespace TestEF5CodeFirstNewDatabase.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class modifyschema : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modifyschema));
        
        string IMigrationMetadata.Id
        {
            get { return "201306170354331_modify-schema"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
